version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: never
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: never
  open-pull-requests-limit: 10
